name: Unittest for CPP neural network implementations.

on:
    push:
        branches: 
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout 
          uses: actions/checkout@v2
        - name: Install Eigen
          run: |
            sudo apt update -y
            sudo apt install libeigen3-dev
            dpkg -S libeigen3-dev
        - name: Compile using Makefile 
          run: make
        - name: Run the test
          run: ./autotest