name: Unittest for CPP neural network implementations.

on:
    push:
        branches: 
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout 
          uses: actions/checkout@v2
        - name: Install Eigen
          run: |
            wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz -O ./include/tempEigen.tar.gz
            tar -xf ./include/tempEigen.tar.gz -C ./include/
            mkdir ./include/Eigen/
            mv ./include/eigen-3.4.0/Eigen/* ./include/Eigen/
            rm ./include/tempEigen.tar.gz
            rm -r ./include/eigen-3.4.0/*
        - name: Compile using Makefile 
          run: make
        - name: Run the test
          run: ./autotest