name: Unittest for CPP neural network implementations.

on:
    push:
        branches: 
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout 
            uses: actions/checkout@v2
        - name: Compile using Makefile 
            run: make
        - name: Run the test
            run: ./autotest